#!/bin/sh
set -e

case "$1" in
  install)
    adduser --system --no-create-home --group multiproxy
    mkdir -p /run/multiproxy
    chown -R multiproxy: /run/multiproxy
    ;;

  upgrade)
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
